### ISSUE TITLE
Using `this` within getOutputFileSlug and generateHTML throws error (v4.0.0-beta.2)

### ISSUE THREAD

**Issue by chrisburnell** [KiwiKilian/eleventy-plugin-og-image#239]
Thanks for all the hard work that went into the version 4 beta! *Love* that there’s caching built-in now! It should really speed up my builds. ❤️

Unfortunately, I’ve been running into problems with the new format of the `getOutputFileSlug` and `generateHTML` options.

The new docs say that I should be able to access the og image instance by using `this` in these functions, e.g.

```javascript
eleventyConfig.addPlugin(EleventyPluginOgImage, {
  generateHTML: () => this.outputUrl(),
});
```

But doing so throws the following error:

```
[11ty] 1. Having trouble writing to "_site/example.html" from "./src/pages/example.md" (via EleventyTemplateError)
[11ty] 2. (./src/eleventy/layouts/root.njk)
[11ty]   EleventyShortcodeError: Error with Nunjucks shortcode `ogImage` (via Template render error)
[11ty] 3. Cannot read properties of undefined (reading 'outputURL') (via Template render error)
[11ty] 
[11ty] Original error stack trace: TypeError: Cannot read properties of undefined (reading 'outputURL')
[11ty]     at OgImage.generateHTML (file:///Users/chrisburnell/Developer/example.com/eleventy.config.js:59:28)
[11ty]     at OgImage.generateHtml (file:///Users/chrisburnell/Developer/example.com/node_modules/eleventy-plugin-og-image/src/OgImage.js:136:48)
[11ty]     at Object.ogImageShortcode (file:///Users/chrisburnell/Developer/example.com/node_modules/eleventy-plugin-og-image/.eleventy.js:125:22)
```

It seems that `this` is undefined in this context. A similar error is thrown when I try using `this` inside my option’s `getOutputFileSlug` function as well.

For clarity’s sake, I’m using the shortcode in my `root.njk` layout like so:

```html
<meta property="og:image" content="{% ogImage './eleventy/layouts/og-image.og.njk', { title: meta_title, description: description, date: date } %}" data-pagefind-meta="image[content]">
```

Apologies if I’m overlooking something here! 😅

**Comment by KiwiKilian** [comment]
Thanks for your flattering feedback!

I was totally expecting this bug report and will update the docs about it. Arrow functions `() => {}` have their own `this`, see info about it on [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#cannot_be_used_as_methods) Therefore it's necessary to declare `generateHTML` and `getOutputFileSlug` as `function`:

```js
eleventyConfig.addPlugin(EleventyPluginOgImage, {
    async generateHTML() {
      return this.outputUrl();
    },
    async getOutputFileSlug() {
      return this.hash();
    },
});
```

Alternatively you are now able to extend the class and overwrite those and others functions:

```js
import { OgImage } from 'eleventy-plugin-og-image/og-image';

class CustomOgImage extends OgImage {
  async generateHTML() {
    return this.outputUrl();
  }
}
```

And pass this class to the plugin

```js

```js
eleventyConfig.addPlugin(EleventyPluginOgImage, {
    OgImage: CustomOgImage
});
```

Hope this fixes the issue and feel free to shoot any questions or problems you might find!

**Comment by chrisburnell** [comment]
Hey @KiwiKilian, many thanks!

Appreciate the info about arrow functions. 😄

I tried both of the methods you suggested above, but unfortunately both didn’t function as expected.

1. Declaring `generateHTML` and `getOutputFileSlug` as functions:
  adasd

**Comment by chrisburnell** [comment]
Hey @KiwiKilian, many thanks for that great response! Very much appreciate the info about arrow functions too! 😄

Unfortunately, I tried both of the suggestions you provided and neither worked as expected.

1. **Declaring `generateHTML` and `getOutputFileSlug` as functions:**

  ```javascript
  import slugify from "@sindresorhus/slugify"

  eleventyConfig.addPlugin(EleventyPluginOgImage, {
    async generateHTML() {
      return this.outputUrl();
    },
    async getOutputFileSlug() {
      return slugify(this.data.page.url);
    },
  });
  ```

  With this method, I was able to define the output file slug as specified, but I was seeing a similar `this.outputURL is not a function` error as before. *This happened whether or not I put the `ogImage` shortcode inside a `setAsync` or directly in my `<meta>` tag.*

  ```bash
  [11ty] 1. Having trouble writing to "_site/example.html" from "./src/pages/example.md" (via EleventyTemplateError)
  [11ty] 2. (./src/eleventy/layouts/root.njk)
  [11ty]   EleventyShortcodeError: Error with Nunjucks paired shortcode `setAsync` (via Template render error)
  [11ty] 3. Error with Nunjucks shortcode `ogImage` (via Template render error)
  [11ty] 4. this.outputURL is not a function (via Template render error)
  [11ty] 
  [11ty] Original error stack trace: TypeError: this.outputURL is not a function
  [11ty]     at OgImage.generateHTML (file:///Users/chrisburnell/Developer/example.com/eleventy.config.js:74:16)
  [11ty]     at OgImage.generateHtml (file:///Users/chrisburnell/Developer/example.com/node_modules/eleventy-plugin-og-image/src/OgImage.js:136:48)
  [11ty]     at Object.ogImageShortcode (file:///Users/chrisburnell/Developer/example.com/node_modules/eleventy-plugin-og-image/.eleventy.js:125:22)
  ```

  It seems like the `outputUrl()` function is not inside `this` here.

2. **Extending `ogImage`:**

  ```javascript
  import slugify from "@sindresorhus/slugify"
  import { OgImage } from "eleventy-plugin-og-image/og-image"

  class CustomOgImage extends OgImage {
    async generateHTML() {
      return this.outputURL()
    }

    async getOutputFileSlug() {
      return slugify(this.data.page.url)
    }
  }

  eleventyConfig.addPlugin(plugins.ogImage, {
    OgImage: CustomOgImage,
  })
  ```

  This method threw no errors, but neither of the functions I defined in my extended `CustomOgImage` class were being used. (I put a `console.log` in the `generateHTML` function as a quick check and it wasn’t printed to the console.)

**Comment by KiwiKilian** [comment]
Could you setup a branch in your repo with the broken code so I could have a look?

At least in your class example there is a typo:
```diff
-outputURL
+outputUrl
```

**Comment by chrisburnell** [comment]
Apologies for the mess and (likely) chunky build time. The branch is here:

https://github.com/chrisburnell/chrisburnell.com/tree/og-images

**Comment by chrisburnell** [comment]
Hey @KiwiKilian, just wanted to jump in here again to say that I just tested with `v4.0.0-beta.3` and this is working just as expected now!

Looks like these issues were indeed a result of my oversights re: capitalisation after all! 😅

**Comment by KiwiKilian** [comment]
No worries, it was a total mess no my side with the capitalization. If it's working fine now feel free to close. And thanks on the feedback, highly appreciate it!

**Comment by KiwiKilian** [comment]
I've fixed the docs regarding this topic. The customize example was also still using an arrow function.

**Comment by KiwiKilian** [comment]
Just a heads up, after some refactorings your config probably should look like this:
```js
	async shortcodeOutput() {
		return this.outputUrl()
	},
	async outputFileSlug() {
		return slugify(this.data.page.url)
	},
```

**Comment by KiwiKilian** [comment]
Hello once again, after the problems in this issue and #252 beeing raised I've moved away from binding pattern and rather pass the `OgImage` instance as a parameter. Your config might update like this:

```js
	async shortcodeOutput(ogImage) {
		return ogImage.outputUrl()
	},
	async outputFileSlug(ogImage) {
		return slugify(ogImage.data.page.url)
	},
```



This also allows arrow functions again. Will probably produce less bug reports 😅.
